pipeline:
  name: apitest
  identifier: apitest
  projectIdentifier: CSETest1
  orgIdentifier: AbhiOrg
  tags:
    tag1: ""
    <+pipeline.variables.fds>: ""
  stages:
    - stage:
        name: shell
        identifier: shell
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: ShellScript_1
                  identifier: ShellScript_1
                  spec:
                    shell: Bash
                    executionTarget: {}
                    source:
                      type: Inline
                      spec:
                        script: |-
                          echo <+trigger.artifact.metadata.fileName>
                          echo <+trigger.artifact.metadata."Accept-Ranges">
                    environmentVariables: []
                    outputVariables: []
                  timeout: 10m
        tags: {}
    - stage:
        name: git
        identifier: git
        description: ""
        type: Pipeline
        spec:
          org: AbhiOrg
          pipeline: gitconfig
          project: CSETest1
          inputSetReferences:
            - dfdrf
  notificationRules:
    - name: test
      identifier: test
      pipelineEvents:
        - type: PipelineEnd
        - type: PipelineFailed
        - type: PipelineSuccess
      notificationMethod:
        type: Email
        spec:
          userGroups: []
          recipients:
            - abhinandan.parashar@harness.io
      enabled: true
  allowStageExecutions: true
