pipeline:
  name: apitest
  identifier: apitest
  projectIdentifier: CSETest1
  orgIdentifier: AbhiOrg
  tags:
    tag1: ""
    <+pipeline.variables.fds>: ""
  stages:
    - stage:
        name: test
        identifier: test
        description: ""
        type: Deployment
        spec:
          deploymentType: Kubernetes
          service:
            serviceRef: k8service
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: ShellScript_1
                  identifier: ShellScript_1
                  spec:
                    shell: Bash
                    executionTarget: {}
                    source:
                      type: Inline
                      spec:
                        script: |
                          # Install Azure CLI
                          sudo rpm --import https://packages.microsoft.com/keys/microsoft.asc
                          sudo rpm -ivh https://packages.microsoft.com/config/rhel/8/packages-microsoft-prod.rpm
                          sudo microdnf install -y azure-cli
                    environmentVariables: []
                    outputVariables:
                      - name: name
                        type: String
                        value: name
                    delegateSelectors:
                      - abhidelegate
                  timeout: 10m
            rollbackSteps: []
          environments:
            metadata:
              parallel: true
            values:
              - environmentRef: ECS_INFRA
                deployToAll: false
                infrastructureDefinitions:
                  - identifier: ee
        tags: {}
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: MarkAsFailure
        when:
          pipelineStatus: All
  variables:
    - name: fds
      type: String
      description: ""
      required: false
      value: <+input>
    - name: key
      type: String
      description: ""
      required: false
      value: https://hooks.slack.com/services/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
    - name: value
      type: String
      description: ""
      required: false
      value: <+<+pipeline.variables.example>.split(",").[0]>
    - name: example
      type: String
      description: ""
      required: false
      value: ("cd-1","cd-2","cd-3")
  notificationRules:
    - name: test
      identifier: test
      pipelineEvents:
        - type: AllEvents
      notificationMethod:
        type: Slack
        spec:
          userGroups: []
          webhookUrl: <+pipeline.variables.key>
      enabled: false
