pipeline:
  name: apitest
  identifier: apitest
  projectIdentifier: CSETest1
  orgIdentifier: AbhiOrg
  tags:
    tag1: ""
    <+pipeline.variables.fds>: ""
  stages:
    - stage:
        name: test
        identifier: test
        description: ""
        type: Deployment
        spec:
          deploymentType: Kubernetes
          service:
            serviceRef: <+input>
            serviceInputs: <+input>
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: ShellScript_1
                  identifier: ShellScript_1
                  spec:
                    shell: Bash
                    executionTarget: {}
                    source:
                      type: Inline
                      spec:
                        script: echo <+inputSet>
                    environmentVariables: []
                    outputVariables:
                      - name: name
                        type: String
                        value: name
                    delegateSelectors:
                      - abhidelegate
                  timeout: 10m
            rollbackSteps: []
          environments:
            metadata:
              parallel: true
            values:
              - environmentRef: ECS_INFRA
                deployToAll: false
                infrastructureDefinitions:
                  - identifier: ee
        tags: {}
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: MarkAsFailure
        when:
          pipelineStatus: Success
    - stage:
        name: b n
        identifier: b_n
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: ShellScript_1
                  identifier: ShellScript_1
                  spec:
                    shell: Bash
                    executionTarget: {}
                    source:
                      type: Inline
                      spec:
                        script: b n
                    environmentVariables: []
                    outputVariables: []
                  timeout: 10m
        tags: {}
    - stage:
        name: tas
        identifier: tas
        description: ""
        type: Deployment
        spec:
          deploymentType: TAS
          service:
            serviceRef: tas
          environment:
            environmentRef: ECS_INFRA
            deployToAll: false
            infrastructureDefinitions:
              - identifier: tas
          execution:
            steps:
              - step:
                  type: BGAppSetup
                  name: BGAppSetup_1
                  identifier: BGAppSetup_1
                  spec:
                    tasInstanceCountType: FromManifest
                    existingVersionToKeep: 3
                    tempRoutes: <+pipeline.variables.example>
                  timeout: 10m
            rollbackSteps: []
        tags: {}
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: Ignore
        variables:
          - name: tanzu
            type: String
            description: ""
            required: false
            value: dfg
  variables:
    - name: fds
      type: String
      description: ""
      required: false
      value: <+input>
    - name: key
      type: String
      description: ""
      required: false
      value: https://hooks.slack.com/services/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
    - name: value
      type: String
      description: ""
      required: false
      value: <+input>
    - name: example
      type: String
      description: ""
      required: false
      value: <+inputSet>
  notificationRules:
    - name: test
      identifier: test
      pipelineEvents:
        - type: AllEvents
      notificationMethod:
        type: Slack
        spec:
          userGroups: []
          webhookUrl: <+pipeline.variables.key>
      enabled: false
  allowStageExecutions: true
