pipeline:
  name: apitest
  identifier: apitest
  projectIdentifier: CSETest1
  orgIdentifier: AbhiOrg
  tags:
    tag1: ""
    <+pipeline.variables.fds>: ""
  stages:
    - parallel:
        - stage:
            name: mat
            identifier: mat
            description: ""
            type: Custom
            spec:
              execution:
                steps:
                  - step:
                      type: ShellScript
                      name: ShellScript_1
                      identifier: ShellScript_1
                      spec:
                        shell: Bash
                        executionTarget: {}
                        source:
                          type: Inline
                          spec:
                            script: |
                              echo "<+matrix.tagsToRun>"
                        environmentVariables: []
                        outputVariables: []
                      timeout: 10m
                      strategy:
                        matrix:
                          tagsToRun: <+stage.variables.tags1.split(',')>
            tags: {}
            variables:
              - name: tags1
                type: String
                description: ""
                required: false
                value: "@1tag,@1taggidy,@1taggiedye"
        - stage:
            name: auto2
            identifier: auto2
            description: ""
            type: Custom
            spec:
              execution:
                steps:
                  - step:
                      type: ShellScript
                      name: ShellScript_1
                      identifier: ShellScript_1
                      spec:
                        shell: Bash
                        executionTarget: {}
                        source:
                          type: Inline
                          spec:
                            script: echo "<+matrix.tagsToExecute2>"
                        environmentVariables: []
                        outputVariables: []
                      timeout: 10m
                      strategy:
                        matrix:
                          tagsToExecute2: <+stage.variables.tags2.split(',')>
            tags: {}
            variables:
              - name: tags2
                type: String
                description: ""
                required: false
                value: <+input>
        - stage:
            name: auto3
            identifier: auto3
            description: ""
            type: Custom
            spec:
              execution:
                steps:
                  - step:
                      type: ShellScript
                      name: ShellScript_1
                      identifier: ShellScript_1
                      spec:
                        shell: Bash
                        executionTarget: {}
                        source:
                          type: Inline
                          spec:
                            script: echo
                        environmentVariables: []
                        outputVariables: []
                      timeout: 10m
                      strategy:
                        matrix:
                          tagsToExecute3: <+stage.variables.tags3.split(",")>
                        when: "!empty(<+stage.variables.tags3>)"
            tags: {}
            variables:
              - name: tags3
                type: String
                description: ""
                required: false
                value: <+input>
    - stage:
        name: k2
        identifier: k2
        description: ""
        type: Deployment
        spec:
          deploymentType: Kubernetes
          service:
            serviceRef: k8service
            serviceInputs:
              serviceDefinition:
                type: Kubernetes
                spec:
                  artifacts:
                    primary:
                      primaryArtifactRef: <+input>
                      sources: <+input>
          environment:
            environmentRef: ECS_INFRA
            deployToAll: false
            infrastructureDefinitions:
              - identifier: two
          execution:
            steps:
              - step:
                  name: Rollout Deployment
                  identifier: rolloutDeployment
                  type: K8sRollingDeploy
                  timeout: 10m
                  spec:
                    skipDryRun: false
                    pruningEnabled: false
            rollbackSteps:
              - step:
                  name: Rollback Rollout Deployment
                  identifier: rollbackRolloutDeployment
                  type: K8sRollingRollback
                  timeout: 10m
                  spec:
                    pruningEnabled: false
        tags: {}
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: StageRollback
  notificationRules: []
  allowStageExecutions: true
  variables:
    - name: k8s
      type: String
      description: ""
      required: false
      value: DockerTestk8
