pipeline:
  name: apitest
  identifier: apitest
  projectIdentifier: CSETest1
  orgIdentifier: AbhiOrg
  tags:
    tag1: ""
    <+pipeline.variables.fds>: ""
  stages:
    - stage:
        name: test
        identifier: test
        description: ""
        type: Deployment
        spec:
          deploymentType: Kubernetes
          service:
            serviceRef: <+input>
            serviceInputs: <+input>
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: ShellScript_1
                  identifier: ShellScript_1
                  spec:
                    shell: Bash
                    executionTarget: {}
                    source:
                      type: Inline
                      spec:
                        script: |
                          # Install Azure CLI using microdnf
                          dnf update
                          dnf install -y https://packages.microsoft.com/config/rhel/8/packages-microsoft-prod.rpm
                          dnf install -y azure-cli
                    environmentVariables: []
                    outputVariables:
                      - name: name
                        type: String
                        value: name
                    delegateSelectors:
                      - abhidelegate
                  timeout: 10m
            rollbackSteps: []
          environments:
            metadata:
              parallel: true
            values:
              - environmentRef: ECS_INFRA
                deployToAll: false
                infrastructureDefinitions:
                  - identifier: ee
        tags: {}
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: MarkAsFailure
        when:
          pipelineStatus: Success
          condition: (<+pipeline.variables.fds> == "abcd" && <+pipeline.variables.value> == "abcde" ) || <+pipeline.variables.example>=="abcd"
    - stage:
        name: b n
        identifier: b_n
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: ShellScript_1
                  identifier: ShellScript_1
                  spec:
                    shell: Bash
                    executionTarget: {}
                    source:
                      type: Inline
                      spec:
                        script: b n
                    environmentVariables: []
                    outputVariables: []
                  timeout: 10m
        tags: {}
  variables:
    - name: fds
      type: String
      description: ""
      required: false
      value: <+input>
    - name: key
      type: String
      description: ""
      required: false
      value: https://hooks.slack.com/services/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
    - name: value
      type: String
      description: ""
      required: false
      value: <+input>
    - name: example
      type: String
      description: ""
      required: false
      value: abc
  notificationRules:
    - name: test
      identifier: test
      pipelineEvents:
        - type: AllEvents
      notificationMethod:
        type: Slack
        spec:
          userGroups: []
          webhookUrl: <+pipeline.variables.key>
      enabled: false
  allowStageExecutions: true
