pipeline:
  name: apitest
  identifier: apitest
  projectIdentifier: CSETest1
  orgIdentifier: AbhiOrg
  tags:
    tag1: ""
    <+pipeline.variables.fds>: ""
  stages:
    - stage:
        name: mat
        identifier: mat
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: ShellScript_1
                  identifier: ShellScript_1
                  spec:
                    shell: Bash
                    executionTarget: {}
                    source:
                      type: Inline
                      spec:
                        script: |
                          echo "<+matrix.tagsToRun>"
                    environmentVariables: []
                    outputVariables: []
                  timeout: 10m
                  strategy:
                    matrix:
                      tagsToRun: <+stage.variables.tags1.split(',')>
        tags: {}
        variables:
          - name: tags1
            type: String
            description: ""
            required: false
            value: <+input>
    - stage:
        name: auto2
        identifier: auto2
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: ShellScript_1
                  identifier: ShellScript_1
                  spec:
                    shell: Bash
                    executionTarget: {}
                    source:
                      type: Inline
                      spec:
                        script: echo "<+matrix.tagsToExecute2>"
                    environmentVariables: []
                    outputVariables: []
                  timeout: 10m
                  strategy:
                    matrix:
                      tagsToExecute2: <+stage.variables.tags2.split(',')>
        tags: {}
        variables:
          - name: tags2
            type: String
            description: ""
            required: false
            value: <+input>
  variables:
    - name: fds
      type: String
      description: ""
      required: false
      value: hey
    - name: key
      type: String
      description: ""
      required: false
      value: <+input>
    - name: something
      type: String
      description: ""
      required: false
      value: <+input>
  notificationRules:
    - name: test6
      identifier: test6
      pipelineEvents:
        - type: AllEvents
      notificationMethod:
        type: Webhook
        spec:
          webhookUrl: <+pipeline.triggeredBy>
      enabled: true
    - name: test
      identifier: test
      pipelineEvents:
        - type: AllEvents
      notificationMethod:
        type: Slack
        spec:
          userGroups: []
          webhookUrl: <+pipeline.variables.key>
      enabled: false
  allowStageExecutions: true
