pipeline:
  name: apitest
  identifier: apitest
  projectIdentifier: CSETest1
  orgIdentifier: AbhiOrg
  tags:
    tag1: ""
    <+pipeline.variables.fds>: ""
  stages:
    - stage:
        name: bs
        identifier: bs
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: ShellScript_1
                  identifier: ShellScript_1
                  spec:
                    shell: Bash
                    executionTarget: {}
                    source:
                      type: Inline
                      spec:
                        script: echo <+<+pipeline.variables.fds>.split(",")>
                    environmentVariables: []
                    outputVariables: []
                  timeout: 10m
        tags: {}
    - stage:
        name: bgp
        identifier: bgp
        description: ""
        type: Deployment
        spec:
          deploymentType: TAS
          service:
            serviceRef: tas
          environment:
            environmentRef: ECS_INFRA
            deployToAll: false
            infrastructureDefinitions:
              - identifier: tas
          execution:
            steps:
              - step:
                  name: BG App Setup
                  identifier: BGAppSetup
                  type: BGAppSetup
                  timeout: 10m
                  spec:
                    tasInstanceCountType: FromManifest
                    existingVersionToKeep: 3
                    additionalRoutes: []
                    tempRoutes: <+pipeline.stages.bgp.variables.two>
              - step:
                  name: App Resize
                  identifier: AppResize
                  type: AppResize
                  timeout: 10m
                  spec:
                    newAppInstances:
                      type: Percentage
                      spec:
                        value: 100
                    oldAppInstances:
                      type: Percentage
                      spec:
                        value: 100
              - step:
                  name: Swap Routes
                  identifier: SwapRoutes
                  type: SwapRoutes
                  timeout: 10m
                  spec:
                    downSizeOldApplication: true
            rollbackSteps:
              - step:
                  name: Swap Rollback
                  identifier: SwapRollback
                  type: SwapRollback
                  timeout: 10m
                  spec:
                    upsizeInActiveApp: true
        tags: {}
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: StageRollback
        variables:
          - name: bgp
            type: String
            description: ""
            required: false
            value: one,two,three,four
          - name: two
            type: String
            description: ""
            required: false
            value: <+pipeline.stages.bgp.variables.bgp>.split(",")
    - stage:
        name: test
        identifier: test
        description: ""
        type: Deployment
        spec:
          deploymentType: Kubernetes
          environments:
            metadata:
              parallel: false
            values:
              - environmentRef: ECS_INFRA
                deployToAll: false
                infrastructureDefinitions:
                  - identifier: ee
          services:
            values:
              - serviceRef: k8service
            metadata:
              parallel: false
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: ShellScript_1
                  identifier: ShellScript_1
                  spec:
                    shell: Bash
                    executionTarget: {}
                    source:
                      type: Inline
                      spec:
                        script: echo ""
                    environmentVariables: []
                    outputVariables: []
                  timeout: 10m
            rollbackSteps: []
        tags: {}
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: MarkAsFailure
  variables:
    - name: fds
      type: String
      description: ""
      required: false
      value: nexus-reports-green.gaiacloud.jpmchase.net,nexus-reports-green.apps.prod.na-6x.gap.jpmchase.net,nexus-access-green.nexus-reports-green.gaiacloud,nexus-access-green.apps.prod.na-6x.gap.jpmchase.net
    - name: key
      type: String
      description: ""
      required: false
      value: <+input>
  notificationRules:
    - name: test6
      identifier: test6
      pipelineEvents:
        - type: AllEvents
      notificationMethod:
        type: Webhook
        spec:
          webhookUrl: <+pipeline.triggeredBy>
      enabled: true
    - name: test
      identifier: test
      pipelineEvents:
        - type: AllEvents
      notificationMethod:
        type: Slack
        spec:
          userGroups: []
          webhookUrl: <+pipeline.variables.key>
      enabled: false
  allowStageExecutions: true
