pipeline:
  name: apitest
  identifier: apitest
  projectIdentifier: CSETest1
  orgIdentifier: AbhiOrg
  tags:
    tag1: ""
    <+pipeline.variables.fds>: ""
  stages:
    - stage:
        name: bs
        identifier: bs
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: ShellScript_1
                  identifier: ShellScript_1
                  spec:
                    shell: Bash
                    executionTarget: {}
                    source:
                      type: Inline
                      spec:
                        script: echo <+<+pipeline.variables.fds>.split(",")>
                    environmentVariables: []
                    outputVariables: []
                  timeout: 10m
        tags: {}
    - stage:
        name: test
        identifier: test
        description: ""
        type: Deployment
        spec:
          deploymentType: Kubernetes
          environments:
            metadata:
              parallel: false
            values:
              - environmentRef: ECS_INFRA
                deployToAll: false
                infrastructureDefinitions:
                  - identifier: ee
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: ShellScript_1
                  identifier: ShellScript_1
                  spec:
                    shell: Bash
                    executionTarget: {}
                    source:
                      type: Inline
                      spec:
                        script: echo <+<+pipeline.stages.test_ECS_INFRA_ee.variables.test>.split(",")>
                    environmentVariables: []
                    outputVariables: []
                  timeout: 10m
            rollbackSteps: []
          service:
            serviceRef: k8service
        tags: {}
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: MarkAsFailure
        variables:
          - name: test
            type: String
            description: ""
            required: false
            value: nexus-reports-green.gaiacloud.jpmchase.net,nexus-reports-green.apps.prod.na-6x.gap.jpmchase.net,nexus-access-green.nexus-reports-green.gaiacloud,nexus-access-green.apps.prod.na-6x.gap.jpmchase.net
  variables:
    - name: fds
      type: String
      description: ""
      required: false
      value: nexus-reports-green.gaiacloud.jpmchase.net,nexus-reports-green.apps.prod.na-6x.gap.jpmchase.net,nexus-access-green.nexus-reports-green.gaiacloud,nexus-access-green.apps.prod.na-6x.gap.jpmchase.net
    - name: key
      type: String
      description: ""
      required: false
      value: <+input>
  notificationRules:
    - name: test6
      identifier: test6
      pipelineEvents:
        - type: AllEvents
      notificationMethod:
        type: Webhook
        spec:
          webhookUrl: <+pipeline.triggeredBy>
      enabled: true
    - name: test
      identifier: test
      pipelineEvents:
        - type: AllEvents
      notificationMethod:
        type: Slack
        spec:
          userGroups: []
          webhookUrl: <+pipeline.variables.key>
      enabled: false
  allowStageExecutions: true
