pipeline:
  name: apitest
  identifier: apitest
  projectIdentifier: CSETest1
  orgIdentifier: AbhiOrg
  tags:
    tag1: ""
    <+pipeline.variables.fds>: ""
  stages:
    - stage:
        name: cds
        identifier: cds
        description: ""
        type: Deployment
        spec:
          deploymentType: NativeHelm
          execution:
            steps:
              - step:
                  type: HelmDeploy
                  name: HelmDeploy_1
                  identifier: HelmDeploy_1
                  spec:
                    skipDryRun: false
                    ignoreReleaseHistFailStatus: false
                  timeout: 10m
            rollbackSteps: []
          service:
            serviceRef: jfrogplatform
            serviceInputs:
              serviceDefinition:
                type: NativeHelm
                spec:
                  manifests:
                    - manifest:
                        identifier: jfrogplatform
                        type: HelmChart
                        spec:
                          store:
                            type: Http
                            spec:
                              connectorRef: <+input>
                          chartVersion: <+input>
                  variables:
                    - name: environment_values_path
                      type: String
                      value: <+input>.allowedValues(shared/default/dev,shared/arti/dev,shared/arti/test,shared/arti/prod)
          environment:
            environmentRef: ECS_INFRA
            deployToAll: false
            infrastructureDefinitions:
              - identifier: helm
        tags: {}
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: StageRollback
  variables:
    - name: fds
      type: String
      description: ""
      required: false
      value: hey
    - name: key
      type: String
      description: ""
      required: false
      value: <+input>
    - name: something
      type: String
      description: ""
      required: false
      value: <+input>
  notificationRules:
    - name: test6
      identifier: test6
      pipelineEvents:
        - type: AllEvents
      notificationMethod:
        type: Webhook
        spec:
          webhookUrl: <+pipeline.triggeredBy>
      enabled: true
    - name: test
      identifier: test
      pipelineEvents:
        - type: AllEvents
      notificationMethod:
        type: Slack
        spec:
          userGroups: []
          webhookUrl: <+pipeline.variables.key>
      enabled: false
  allowStageExecutions: true
