pipeline:
  name: dummypipeline
  identifier: dummypipeline
  projectIdentifier: CSETest1
  orgIdentifier: AbhiOrg
  tags: {}
  stages:
    - stage:
        name: check
        identifier: check
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: ShellScript_1
                  identifier: ShellScript_1
                  spec:
                    shell: Bash
                    executionTarget: {}
                    source:
                      type: Inline
                      spec:
                        script: jq '.name' data.json
                    environmentVariables: []
                    outputVariables: []
                  timeout: 10m
          environment:
            environmentRef: ECS_INFRA
            deployToAll: false
            infrastructureDefinitions:
              - identifier: helm
        tags: {}
    - stage:
        name: ssh
        identifier: ssh
        description: ""
        type: Deployment
        spec:
          deploymentType: Ssh
          service:
            serviceRef: ssh
            serviceInputs:
              serviceDefinition:
                type: Ssh
                spec:
                  artifacts:
                    primary:
                      primaryArtifactRef: <+input>
                      sources: <+input>
          environment:
            environmentRef: ssh
            deployToAll: false
            infrastructureDefinitions:
              - identifier: ssh
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: ShellScript_1
                  identifier: ShellScript_1
                  spec:
                    shell: Bash
                    executionTarget: {}
                    source:
                      type: Inline
                      spec:
                        script: echo hey
                    environmentVariables: []
                    outputVariables: []
                  timeout: 10m
            rollbackSteps: []
        tags: {}
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: StageRollback
        strategy:
          repeat:
            items: <+stage.output.hosts>
  variables:
    - name: one
      type: String
      description: ""
      required: false
      value: k8service
    - name: oneK8S
      type: String
      description: ""
      required: false
      value: "true"
  allowStageExecutions: true
