pipeline:
  name: dummypipeline
  identifier: dummypipeline
  projectIdentifier: CSETest1
  orgIdentifier: AbhiOrg
  tags: {}
  stages:
    - stage:
        name: check
        identifier: check
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: ShellScript_1
                  identifier: ShellScript_1
                  spec:
                    shell: Bash
                    executionTarget: {}
                    source:
                      type: Inline
                      spec:
                        script: |
                          echo '<+secrets.getValue("account.abhishek")>' > file.json
                          cat file.json
                    environmentVariables: []
                    outputVariables: []
                  timeout: 10m
              - step:
                  type: HarnessApproval
                  name: HarnessApproval_1
                  identifier: HarnessApproval_1
                  spec:
                    approvalMessage: Please review the following information and approve the pipeline progression <+pipeline.variables.oneK8S>
                    includePipelineExecutionHistory: true
                    isAutoRejectEnabled: false
                    approvers:
                      userGroups:
                        - abhi
                      minimumCount: 1
                      disallowPipelineExecutor: false
                    approverInputs:
                      - name: "input "
                        defaultValue: input
                  timeout: 1d
          environment:
            environmentRef: ECS_INFRA
            deployToAll: false
            infrastructureDefinitions:
              - identifier: helm
        tags: {}
  variables:
    - name: one
      type: String
      description: ""
      required: false
      value: k8service
    - name: oneK8S
      type: String
      description: ""
      required: false
      value: "true"
  allowStageExecutions: true
