pipeline:
  name: dummypipeline
  identifier: dummypipeline
  projectIdentifier: CSETest1
  orgIdentifier: AbhiOrg
  tags: {}
  stages:
    - stage:
        name: check
        identifier: check
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: ShellScript_1
                  identifier: ShellScript_1
                  spec:
                    shell: Bash
                    executionTarget: {}
                    source:
                      type: Inline
                      spec:
                        script: |-
                          echo <+stage.output.hosts>.split(",")
                          echo "heko"
                          echo <+stage.output.hosts>
                    environmentVariables: []
                    outputVariables: []
                  timeout: 10m
                  failureStrategies:
                    - onFailure:
                        errors:
                          - AllErrors
                        action:
                          type: Ignore
                  strategy:
                    repeat:
                      items: <+stage.output.hosts>
          environment:
            environmentRef: ssh
            deployToAll: false
            infrastructureDefinitions:
              - identifier: fssh
        tags: {}
        variables:
          - name: hostsname
            type: String
            description: ""
            required: false
            value: <+input>
    - stage:
        name: g
        identifier: g
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: ShellScript_1
                  identifier: ShellScript_1
                  spec:
                    shell: Bash
                    executionTarget: {}
                    source:
                      type: Inline
                      spec:
                        script: echo "hey"
                    environmentVariables: []
                    outputVariables: []
                  timeout: 10m
        tags: {}
        strategy:
          repeat:
            items: <+pipeline.stages.check.variables.hostsname>
  variables:
    - name: one
      type: String
      description: ""
      required: false
      value: k8service
    - name: oneK8S
      type: String
      description: ""
      required: false
      value: "true"
  allowStageExecutions: true
