pipeline:
  name: dummypipeline
  identifier: dummypipeline
  projectIdentifier: CSETest1
  orgIdentifier: AbhiOrg
  tags: {}
  stages:
    - stage:
        name: check
        identifier: check
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: ShellScript_1
                  identifier: ShellScript_1
                  spec:
                    shell: Bash
                    executionTarget: {}
                    source:
                      type: Inline
                      spec:
                        script: echo <+pipeline.execution.url>
                    environmentVariables: []
                    outputVariables: []
                  timeout: 10m
          environment:
            environmentRef: ECS_INFRA
            deployToAll: false
            infrastructureDefinitions:
              - identifier: helm
        tags: {}
  variables:
    - name: one
      type: String
      description: ""
      required: false
      value: k8service
    - name: oneK8S
      type: String
      description: ""
      required: false
      value: "true"
  allowStageExecutions: true
