pipeline:
  name: nondef
  identifier: nondef
  projectIdentifier: CSETest1
  orgIdentifier: AbhiOrg
  tags: {}
  stages:
    - stage:
        name: vv
        identifier: vv
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: ShellScript_1
                  identifier: ShellScript_1
                  spec:
                    shell: Bash
                    executionTarget: {}
                    source:
                      type: Inline
                      spec:
                        script: |-
                          curl -i -X POST \
                            'https://app.harness.io/ccm/api/governance/enqueueAdhocV2?accountIdentifier=akx2lmy5SnOFm549xPhFKQ' \
                            -H 'Content-Type: application/json' \
                            -H 'x-api-key: pat.akx2lmy5SnOFm549xPhFKQ.67dce6ef6b95c23f61fc86d6.myVN6vO04RkumbbpeRS8' \
                            -d '{
                              "targetAccounts": [
                                "915632791698"
                              ],
                              "targetRegions": [
                                "us-east-1"
                              ],
                              "ruleId": "65d5b67bf9649b3e833aa4c7",
                              "isDryRun": true
                            }'
                    environmentVariables: []
                    outputVariables: []
                  timeout: 10m
        tags: {}
