pipeline:
  identifier: sample
  name: sample
  projectIdentifier: CSETest1
  orgIdentifier: AbhiOrg
  tags: {}
  stages:
    - stage:
        identifier: auto2
        type: Custom
        name: auto2
        description: ""
        spec:
          execution:
            steps:
              - step:
                  identifier: ShellScript_1
                  type: ShellScript
                  name: ShellScript_1
                  spec:
                    shell: Bash
                    executionTarget: {}
                    source:
                      type: Inline
                      spec:
                        script: |
                          echo <+secrets.getValue("account.azurevault")>
                    environmentVariables: []
                    outputVariables: []
                  timeout: 10m
        tags: {}
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: Ignore
        variables:
          - name: tags2
            type: String
            description: tags to run in auto2
            required: false
            value: "@2taggo,@2tagjgj"
  flowControl:
    barriers:
      - name: njk
        identifier: njk
