pipeline:
  name: t
  identifier: t
  projectIdentifier: CSETest1
  orgIdentifier: AbhiOrg
  tags: {}
  stages:
    - stage:
        name: ecs
        identifier: ecs
        description: ""
        type: Deployment
        spec:
          deploymentType: ECS
          service:
            serviceRef: NewECS
            serviceInputs:
              serviceDefinition:
                type: ECS
                spec:
                  artifacts:
                    primary:
                      primaryArtifactRef: <+input>
                      sources: <+input>
          environment:
            environmentRef: ECS_INFRA
            deployToAll: false
            infrastructureDefinitions:
              - identifier: ecs_INFRA
          execution:
            steps:
              - step:
                  type: EcsRollingDeploy
                  name: EcsRollingDeploy_1
                  identifier: EcsRollingDeploy_1
                  spec:
                    sameAsAlreadyRunningInstances: false
                    forceNewDeployment: false
                  timeout: 10m
            rollbackSteps:
              - step:
                  name: ECS Basic Rollback
                  identifier: EcsBasicRollback
                  type: EcsBasicRollback
                  timeout: 10m
                  spec: {}
        tags: {}
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: StageRollback
  variables:
    - name: run
      type: String
      description: ""
      required: false
      value: <+input>
