AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template to create an S3 bucket named 'testcf' without versioning

Resources:
  MyS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: testcf_abhi_amit
      VersioningConfiguration:
        Status: Suspended

Outputs:
  BucketNameOutput:
    Description: Name of the created S3 bucket
    Value: !Ref MyS3Bucket

  BucketArn:
    Description: ARN of the created S3 bucket
    Value: !GetAtt MyS3Bucket.Arn
